### ISSUE TITLE
Code doesn't work.

### ISSUE THREAD

**Issue by KleinerNull** [JackCDK/browser-bomb#1]
Get this message after inserting an integer:

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-4-7cac1f76b50d> in <module>()
         35 # websi = input("[?] What site do you want to use?:")
         36 
    ---> 37 snum = int(input("[?] How many times do you want to spam your pc?: "))
         38 time.sleep(5)
         39 for word in ['spaming'] * snum:

    ValueError: invalid literal for int() with base 10: '0x8'

Also it isn't python3 compatible...

**Comment by JackCDK** [comment]
Ok I've  fixed it for python3

[Here(https://github.com/JackCDK/browser-bomb/blob/master/versions/python3/bbomb_1.0.5_p3.py)

**Comment by KleinerNull** [comment]
@JackCDK 

Nice, you actually fixed an issude. I hope you know that this was a little joke. Just wanted to point you in the directions of pyton versions and proper input validation.

Unfortunally, it looks like you just copy pasted some pattern into your code because `while ... else` and `except ... print ... continue` a very uncommon pattern. I will commit you the cleaner pattern, so you can learn how to use git the proper way. ;)

But the integer 0x8 ist still not working.
